class TestBot{constructor(){this.context=this.detectMetaValues();this.context.country=void 0;this.context.lang=this.detectLang();this.actionSettings={};this.rules=[];this.likeMessages=[];this.dislikeMessages=[];this.neutralThoughtfulPhrases=[];this.finalPhrases=[];this.internationalFirstNames=[];this.internationalLastNames=[]}detectCountryAndProceed(){const a=this;fetch("https://api.country.is").then(b=>b.json()).then(b=>{this.context.country=b.country}).catch(b=>{this.context.country=void 0}).finally(()=>
{a.simulateReadersActivities()})}detectLang(){const a=document.querySelectorAll("html")[0].getAttribute("lang");return a?a:"en"}detectMetaValues(){const a={};document.querySelectorAll("meta").forEach(b=>{const c=b.getAttribute("name");b=b.getAttribute("content");c&&b&&(a[c]=b)});return a}getContext(){return this.context}getScriptURL(){return this.context["testbot.testdata.script"]}isStrict(a){a=String(a);return a.endsWith(".id")||a.endsWith(".uid")||a.endsWith(".oid")||a.endsWith("verno")||a.endsWith("datetime")}normalizeString(a){return String(a).toUpperCase()}matchContextProp(a,
b,c){return b.hasOwnProperty(a)?this.isStrict(a)?b[a]==c[a]:-1!=this.normalizeString(b[a]).indexOf(this.normalizeString(c[a])):!1}matchContext(a,b){let c=0;if(!b)return 0;for(const d in b){if(!this.matchContextProp(d,a,b))return 0;c++}return c}getDefaultResponse(){let a={issue_probabilities:{bounce:.5,like:.01,likeMessage:.001,dislike:.05,dislikeMessage:.005,stuck:.1},link_appeal_rates:[]};for(const b of this.rules)if(!b.trigger){a=b.response;break}return a}chooseResponse(a){let b=this.getDefaultResponse(),
c=0;for(const d of this.rules){let e=this.matchContext(a,d.trigger);e>c&&(c=e,b=d.response)}return b}getRandomInteger(a,b){return Math.floor(Math.random()*(b-a+1)+a)}getRandomNormalInteger(a,b){let c=0;for(let d=0;6>d;d++)c+=this.getRandomInteger(a,b);return Math.floor(c/6)}evaluateAppealRate(a){let b=1;const c=this.getDefaultResponse();let d=String(a.getAttribute("href")).toLowerCase();a=String(a.textContext).toLowerCase();for(const e of c.link_appeal_rates)if(-1!=d.indexOf(e.pattern)||-1!=a.indexOf(e.pattern)){b=
e.rate;break}return b}browseToNextPage(){let a=document.getElementsByTagName("a");if(0==a.length)history.back();else{var b=[],c=0;for(var d=0;d<a.length;d++)c+=this.evaluateAppealRate(a[d]),b[d]=c;d=null;c*=Math.random();for(let e=0;e<a.length;e++)if(c<b[e]){d=a[e];break}d&&d.click()}}getRandomItem(a){return a[this.getRandomInteger(0,a.length-1)]}getLocalMessages(a,b){b=b?b:this.detectLang();return a[b]?a[b]:a.en}getRandomMessage(a){let b=[];.1>=Math.random()&&b.push(this.getRandomItem(this.getLocalMessages(this.neutralThoughtfulPhrases)));
for(let c=0;c<this.getRandomInteger(1,3);c++)b.push(this.getRandomItem(this.getLocalMessages(a)));.1>=Math.random()&&b.push(this.getRandomItem(this.getLocalMessages(this.neutralThoughtfulPhrases)));b.push(this.getRandomItem(this.getLocalMessages(this.finalPhrases))+",");b.push(this.getRandomItem(this.getLocalMessages(this.internationalFirstNames)));b.push(this.getRandomItem(this.getLocalMessages(this.internationalLastNames)));return[{varname:"icap.action.message",parsable_value:b.join(" ")}]}getDislikeMessage(){return this.getRandomMessage(this.dislikeMessages)}getLikeMessage(){return this.getRandomMessage(this.likeMessages)}getRandomEventName(a,
b){const c=[];let d=0;for(var e in a)d+=a[e],c.push({eventName:e,eventRate:d});a=Math.random();for(e=0;e<c.length;e++)if(a<=c[e].eventRate){b=c[e].eventName;break}return b}getArbitraryUserActionType(a){return this.getRandomEventName(a,"normal")}simulateReadersActivities(){var a=this.getContext();const b=this.chooseResponse(a);console.table(a);console.table(b.issue_probabilities);a=0;let c="";switch(this.getArbitraryUserActionType(b.issue_probabilities)){case "bounce":console.log("Bounce");a=this.getRandomInteger(this.actionSettings.bounce_min,
this.actionSettings.bounce_max);break;case "like":console.log("Like");GLOBAL_ICAP_REPORTER.addActionMeasurement("LIKE");break;case "likeMessage":console.log("Like and a message");c=this.getLikeMessage();console.log(c[0].parsable_value);GLOBAL_ICAP_REPORTER.addActionMeasurement("LIKE",c);break;case "dislike":console.log("Dislike");GLOBAL_ICAP_REPORTER.addActionMeasurement("DISLIKE");break;case "dislikeMessage":console.log("Dislike and a message");c=this.getDislikeMessage();console.log(c[0].parsable_value);
GLOBAL_ICAP_REPORTER.addActionMeasurement("DISLIKE",c);break;case "stuck":console.log("Stuck");a=this.getRandomInteger(this.actionSettings.stuck_min,this.actionSettings.stuck_max);break;default:console.log("Normal")}0==a&&(a=this.getRandomNormalInteger(this.actionSettings.bounce_max,this.actionSettings.stuck_min));console.log("Delay:",a,"sec.");setTimeout(()=>{this.browseToNextPage()},1E3*a)}loadScriptAndProceed(){console.log("Loading...");const a=this.getScriptURL();fetch(a).then(b=>b.json()).then(b=>
{this.actionSettings=b.action_settings;this.rules=b.rules;this.likeMessages=b.like_messages;this.dislikeMessages=b.dislike_messages;this.neutralThoughtfulPhrases=b.neutral_thoughtful_phrases;this.finalPhrases=b.final_phrases;this.internationalFirstNames=b.international_first_names;this.internationalLastNames=b.international_last_names;this.detectCountryAndProceed()}).catch(b=>{console.log()})}run(){console.log("The iCAP test bot is here!");this.loadScriptAndProceed()}}var GLOBAL_TESTBOT=new TestBot;
GLOBAL_TESTBOT.run();
